[2025-06-28T11:25:14.494+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-28T11:25:14.516+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_log_processing.log_extraction manual__2025-06-28T11:25:10.590062+00:00 [queued]>
[2025-06-28T11:25:14.527+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_log_processing.log_extraction manual__2025-06-28T11:25:10.590062+00:00 [queued]>
[2025-06-28T11:25:14.527+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-06-28T11:25:15.226+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): log_extraction> on 2025-06-28 11:25:10.590062+00:00
[2025-06-28T11:25:15.245+0000] {standard_task_runner.py:63} INFO - Started process 50 to run task
[2025-06-28T11:25:15.258+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'etl_log_processing', 'log_extraction', 'manual__2025-06-28T11:25:10.590062+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/logs_dag.py', '--cfg-path', '/tmp/tmpza_i__xm']
[2025-06-28T11:25:15.266+0000] {standard_task_runner.py:91} INFO - Job 2: Subtask log_extraction
[2025-06-28T11:25:15.404+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_log_processing.log_extraction manual__2025-06-28T11:25:10.590062+00:00 [running]> on host 71ba61a51b69
[2025-06-28T11:25:15.503+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Hoang' AIRFLOW_CTX_DAG_ID='etl_log_processing' AIRFLOW_CTX_TASK_ID='log_extraction' AIRFLOW_CTX_EXECUTION_DATE='2025-06-28T11:25:10.590062+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-28T11:25:10.590062+00:00'
[2025-06-28T11:25:15.505+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-28T11:25:15.578+0000] {logging_mixin.py:188} INFO - /opt/airflow/data//20250628_log.csv
[2025-06-28T11:25:15.579+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-28T11:25:15.580+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/pipelines/log_pipeline.py", line 12, in log_pipeline
    events = connect_API(API_URL)
TypeError: connect_API() missing 1 required positional argument: 'headers'
[2025-06-28T11:25:15.598+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=etl_log_processing, task_id=log_extraction, run_id=manual__2025-06-28T11:25:10.590062+00:00, execution_date=20250628T112510, start_date=20250628T112514, end_date=20250628T112515
[2025-06-28T11:25:15.616+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 2 for task log_extraction (connect_API() missing 1 required positional argument: 'headers'; 50)
[2025-06-28T11:25:15.640+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-28T11:25:15.665+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-28T11:25:15.666+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
